baseera/urls.py
from django.conf.urls import include , url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^polls/', include('polls.urls')),
]

polls/urls.py
from django.conf.urls import url
from . import views

app_name='polls'
urlpatterns = [
 	#/polls/
 	url(r'^$' , views.IndexView.as_view(),name='index'),
 	#/polls/id/
 	url(r'^(?P<pk>[0-9]+)/$', views.DetailView.as_view(), name='detail'),
 	#/polls/id/results/
 	url(r'^(?P<pk>[0-9]+)/results/$', views.ResultsView.as_view(), name='results'),
 	#/polls/id/vote/
 	url(r'^(?P<question_id>[0-9]+)/vote/$', views.vote, name='vote'),
 	#/polls/add/
 	url(r'^question/add/$', views.QuestionCreate.as_view(), name='question-add'),
 	#/polls/id/update/
 	url(r'^(?P<pk>[0-9]+)/update/$', views.QuestionUpdate.as_view(), name='question-update'),
 	#/polls/id/delete/
 	url(r'^(?P<pk>[0-9]+)/delete/$', views.QuestionDelete.as_view(), name='question-delete'),
 	#/polls/id/mydel/
 	url(r'^(?P<question_id>[0-9]+)/mydel/$', views.mydel, name='mydel'),
 ]

polls/models.py
from __future__ import unicode_literals
import datetime
from django.core.urlresolvers import reverse
from django.db import models
from django.utils import timezone

# Create your models here.

class Question(models.Model):
	question_text=models.CharField(max_length=200)
	pub_date=models.DateTimeField('date published')

	def get_absolute_url(self):
		return reverse("polls:detail", kwargs={'pk':self.pk})

	def __str__(self):
		return self.question_text

	def was_published_recently(self):
		now=timezone.now()
		return now - datetime.timedelta(days=1) <= self.pub_date <= now


class Choice(models.Model):
	question=models.ForeignKey(Question,on_delete=models.CASCADE)
	choice_text=models.CharField(max_length=200)
	votes=models.IntegerField(default=0)

	def __str__(self):
		return self.choice_text

polls/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, Http404, HttpResponseRedirect
from .models import Question, Choice
from django.template import loader
from django.urls import reverse
from django.views import generic
from django.utils import timezone
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy

# Create your views here.


class IndexView(generic.ListView):
	template_name='polls/index.html'
	context_object_name='latest_question_list'

	def get_queryset(self):
		return Question.objects.filter( pub_date__lte=timezone.now() ).order_by('-pub_date')[:5]

class DetailView(generic.DetailView):
	template_name='polls/detail.html'
	model=Question


class ResultsView(generic.DetailView):
	template_name='polls/results.html'
	model=Question


def vote(request,question_id):
	question=get_object_or_404(Question,pk=question_id)
	try:
		selected_choice=question.choice_set.get(pk=request.POST['choice'])
	except (KeyError, Choice.DoesNotExist):
		return render(request,'polls/detail.html',{'question':question,
													'error_message':"choice does not exist",})
	else:
		selected_choice.votes+=1
		selected_choice.save()
		return HttpResponseRedirect(reverse('polls:results', args=(question.id,)))

class QuestionCreate(CreateView):
	model=Question
	fields=['question_text','pub_date']

class QuestionUpdate(UpdateView):
	model=Question
	fields=['question_text','pub_date']

class QuestionDelete(DeleteView):
	model=Question
	success_url = reverse_lazy('polls:index')

def mydel (request,question_id):
	question=get_object_or_404(Question,pk=question_id)
	question.delete()
	latest_question_list=Question.objects.filter( pub_date__lte=timezone.now() ).order_by('-pub_date')[:5]
	return render(request,'polls/index.html',{'latest_question_list':latest_question_list})

polls/templates/polls/detail.html
{%load static%}
<link rel="stylesheet" type="text/css" href="{% static "polls/style.css"%}"/>
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">

<nav class="navbar navbar-default">
	<div class="container-fluid">

		<div class="navbar-header">
			<a class="navbar-brand" href="{% url "polls:index" %}">Home</a>
		</div>
	</div>
</nav>
<h1>{{question.question_text}}</h1>
{%if error_message%}<p><strong>{{error_message}}</strong></p>{% endif %}

<form action="{% url 'polls:vote' question.id %}" method="post">
	{% csrf_token %}
	{% for choice in question.choice_set.all %}
		<input type="radio" name="choice" id="choice{{forloop.counter}}" value={{choice.id}} />
		<label for="choice{{forloop.counter}}">{{choice.choice_text}}</label><br />
	{%endfor%}
	<input type="submit" value="vote" />
</form>
	

polls/templates/polls/form_template.html
{% for field in form %}
    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
            <span class="text-danger small">{{ field.errors }}</span>
        </div>
        <label class="control-label col-sm-2" for="song_title">{{ field.label_tag }}</label>
        <div class="col-sm-10">{{ field }}</div>
    </div>
{% endfor %}

polls/templates/polls/index.html
{%load static%}
<link rel="stylesheet" type="text/css" href="{% static "polls/style.css" %}"/>
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">

<nav class="navbar navbar-default">
	<div class="container-fluid">

		<div class="navbar-header">
			<a class="navbar-brand" href="{% url "polls:index" %}">Home</a>
		</div>
	</div>

	<ul class="nav navbar-nav navbar-right">
		<li>
			<a href="{% url 'polls:question-add' %}">
				<span class="glyphicon glyphicon-plus" aria-hidden="true"></span>&nbsp; Add Question
			</a>
		</li>
	</ul>
</nav>
{%if latest_question_list %}
	<ul>
		{%for question in latest_question_list%}
		<li>
			<a href={% url 'polls:detail' question.id%}>{{question.question_text}}</a>
			<a href={% url 'polls:mydel' question.id %}>
					<span class="glyphicon glyphicon-plus" aria-hidden="true"></span>&nbsp; Delete Question</a>
			<a href="{% url 'polls:question-update' question.id %}">
					<span class="glyphicon glyphicon-plus" aria-hidden="true"></span>&nbsp; Update Question</a>
		</li>

		{%endfor%}
	</ul>
{%else%}
	<h1>No polls are available.</h1>
{%endif%}

polls/templates/polls/question_form.html
<div class="container-fluid">

    <div class="row">

        <div class="col-sm-12 col-md-7">
            <div class="panel panel-default">
                <div class="panel-body">
                    <h3>Add a New Question</h3>
                    {% if error_message %}
                        <p><strong>{{ error_message }}</strong></p>
                    {% endif %}
                    <form class="form-horizontal" role="form" action="" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {% include 'polls/form_template.html' %}
                        <div class="form-group">
                            <div class="col-sm-offset-2 col-sm-10">
                                <button type="submit" class="btn btn-success">Submit</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

polls/templates/polls/results.html
{%load static%}
<link rel="stylesheet" type="text/css" href="{% static "polls/style.css"%}"/>
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">

<nav class="navbar navbar-default">
	<div class="container-fluid">

		<div class="navbar-header">
			<a class="navbar-brand" href="{% url "polls:index" %}">Home</a>
		</div>
	</div>
</nav>
<h1>{{question.question_text}}</h1>
<ul>
{% for choice in question.choice_set.all %}
	<li>{{  choice.choice_text }} -- {{choice.votes}} vote{{ choice.votes|pluralize }}</li>
{% endfor %}
</ul>
<a href="{% url 'polls:detail' question.id%}"><strong>vote again<strong></a>